workflows:
  ios_testflight:
    name: iOS TestFlight (automatic signing)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      vars:
        # REQUIRED: Replace with your app's bundle identifier
        BUNDLE_ID: com.masader.remontada

        # App Store Connect credentials (required by Codemagic validator)
        APP_STORE_CONNECT_ISSUER_ID: "0f0920a6-19c1-4f96-a66d-e3b868fcdfde"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "ZPPXRWNQ3C"
        APP_STORE_CONNECT_PRIVATE_KEY: |-
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPpFpFRLKnr/BPhBN
          O/5Ngv1IJ4LkulhVhMFuVQxRf0OgCgYIKoZIzj0DAQehRANCAATDS8h9azww64Ao
          wKJMRFkZIkLOarTpP4n96N3T+39mzS8jPHYuwO+6Nif58oVSTxRY66seoiP+6P3r
          Av86xywb
          -----END PRIVATE KEY-----

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Show Flutter & Xcode versions
        script: |
          flutter --version
          xcodebuild -version

      - name: Install dependencies
        script: |
          flutter pub get

      - name: Prepare automatic code signing (fetch/create certs & profiles)
        script: |
          # Fetch or create signing assets for App Store distribution
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --bundle-id "$BUNDLE_ID" \
            --team-id "8Q82C9364G" \
            --create

          # Apply the fetched provisioning profiles to the Xcode project
          xcode-project use-profiles

      - name: Build iOS IPA (Release)
        script: |
          # Build a signed .ipa using Flutter
          flutter build ipa --release

      - name: Verify build artifacts
        script: |
          ls -la build/ios/ipa || true

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app

    publishing:
      app_store_connect:
        api_key: |
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPpFpFRLKnr/BPhBN
          O/5Ngv1IJ4LkulhVhMFuVQxRf0OgCgYIKoZIzj0DAQehRANCAATDS8h9azww64Ao
          wKJMRFkZIkLOarTpP4n96N3T+39mzS8jPHYuwO+6Nif58oVSTxRY66seoiP+6P3r
          Av86xywb
          -----END PRIVATE KEY-----
        key_id: "ZPPXRWNQ3C"
        issuer_id: "0f0920a6-19c1-4f96-a66d-e3b868fcdfde"
        submit_to_testflight: true
        # Optional: list of TestFlight beta groups to auto-assign
        # beta_groups:
        #   - Internal Testers

